# Generated by Django 3.0.3 on 2020-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
