# Generated by Django 3.0.3 on 2020-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0005_auto_20200404_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Some Image', max_length=255),
        ),
    ]
